### Input
# input rgba image path (default to None, can be load in GUI too)
input: 
# input text prompt (default to None, can be input in GUI too)
prompt:
negative_prompt:
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image 
elevation: 0
# reference image resolution
ref_size: 512
# density thresh for mesh extraction
density_thresh: 1

normal_ckpt_path: ./checkpoints/omnidata_dpt_normal_v2.ckpt
### Output
outdir: logs
mesh_format: obj
save_path: ???

### Training
# use mvdream instead of sd 2.1
mvdream: False
# use imagedream
imagedream: False
# use stable-zero123 instead of zero123-xl
stable_zero123: False 
# use sv3d  
sv3d: True 
# use normal estimation 
dpt: False
# guidance loss weights (0 to disable)
lambda_sd: 0
lambda_zero123: 0
lambda_normal: 0.05 
lambda_normal_dpt: 0.05  
lambda_dist: 100 
lambda_dssim: 0.2
lambda_mask: 1.0

# warmup rgb supervision for image-to-3d
warmup_rgb_loss: False
# training batch size per iter
batch_size: 1
# training iterations for stage 1
iters: 10000
# whether to linearly anneal timestep
anneal_timestep: True
# training iterations for stage 2
iters_refine: 50
# training camera radius
radius: 2
# training camera fovy
fovy: 49.1 # align with zero123 rendering setting (ref: https://github.com/cvlab-columbia/zero123/blob/main/objaverse-rendering/scripts/blender_script.py#L61
# training camera min elevation
min_ver: -30
# training camera max elevation
max_ver: 30
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: False
white_background: True 
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.5


### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

### Gaussian splatting
num_pts: 5000
sh_degree: 3
position_lr_init: 0.00016
position_lr_final:  0.0000016
position_lr_delay_mult: 0.01
position_lr_max_steps: 10000
feature_lr: 0.0025
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.001
percent_dense: 0.01
density_start_iter: 500
density_end_iter: 15000
densification_interval: 100
opacity_reset_interval: 3000
densify_grad_threshold: 0.0002
densify_min_opacity: 0.05 
densify_extent: 4
densify_max_screen_size: 1 

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2